# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/guanshangl0g62fht}

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${APP_DB_URL:jdbc:mysql://127.0.0.1:3306/guanshangl0g62fht?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:971021}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:/static/
  mail:
    host: ${APP_MAIL_HOST:smtp.qq.com}
    port: ${APP_MAIL_PORT:465}
    username: ${APP_MAIL_USERNAME:}
    password: ${APP_MAIL_PASSWORD:}
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.entity
  global-config:
    id-type: 1
    field-strategy: 1
    db-column-underline: true
    refresh-mapper: false
    logic-delete-value: -1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: "null"
